DROP DATABASE IF EXISTS :db_name;
CREATE DATABASE :db_name ENCODING 'UTF8';
\c :db_name
SET client_encoding = 'UTF8';

GRANT ALL PRIVILEGES ON DATABASE :db_name TO :db_user;

-- teams
CREATE TABLE teams (
    code INTEGER,
    draw INTEGER,
    form TEXT,
    id INTEGER PRIMARY KEY,
    loss INTEGER,
    name TEXT,
    played INTEGER,
    points INTEGER,
    position INTEGER,
    short_name TEXT,
    strength INTEGER,
    team_division INTEGER,
    unavailable BOOLEAN,
    win INTEGER,
    strength_overall_home INTEGER,
    strength_overall_away INTEGER,
    strength_attack_home INTEGER,
    strength_attack_away INTEGER,
    strength_defence_home INTEGER,
    strength_defence_away INTEGER,
    pulse_id INTEGER
);

-- elements
CREATE TABLE elements (
    id INTEGER PRIMARY KEY,
    can_transact BOOLEAN,
    can_select BOOLEAN,
    chance_of_playing_next_round INTEGER,
    chance_of_playing_this_round INTEGER,
    code INTEGER,
    cost_change_event INTEGER,
    cost_change_event_fall INTEGER,
    cost_change_start INTEGER,
    cost_change_start_fall INTEGER,
    dreamteam_count INTEGER,
    element_type INTEGER,
    ep_next TEXT,
    ep_this TEXT,
    event_points INTEGER,
    first_name TEXT,
    form TEXT,
    in_dreamteam BOOLEAN,
    news TEXT,
    news_added TIMESTAMP,
    now_cost INTEGER,
    photo TEXT,
    points_per_game TEXT,
    removed BOOLEAN,
    second_name TEXT,
    selected_by_percent TEXT,
    special BOOLEAN,
    squad_number INTEGER,
    status TEXT,
    team INTEGER,
    team_code INTEGER,
    total_points INTEGER,
    transfers_in INTEGER,
    transfers_in_event INTEGER,
    transfers_out INTEGER,
    transfers_out_event INTEGER,
    value_form TEXT,
    value_season TEXT,
    web_name TEXT,
    region INTEGER,
    team_join_date DATE,
    birth_date DATE,
    has_temporary_code BOOLEAN,
    opta_code TEXT,
    minutes INTEGER,
    goals_scored INTEGER,
    assists INTEGER,
    clean_sheets INTEGER,
    goals_conceded INTEGER,
    own_goals INTEGER,
    penalties_saved INTEGER,
    penalties_missed INTEGER,
    yellow_cards INTEGER,
    red_cards INTEGER,
    saves INTEGER,
    bonus INTEGER,
    bps INTEGER,
    influence TEXT,
    creativity TEXT,
    threat TEXT,
    ict_index TEXT,
    clearances_blocks_interceptions INTEGER,
    recoveries INTEGER,
    tackles INTEGER,
    defensive_contribution INTEGER,
    starts INTEGER,
    expected_goals TEXT,
    expected_assists TEXT,
    expected_goal_involvements TEXT,
    expected_goals_conceded TEXT,
    influence_rank INTEGER,
    influence_rank_type INTEGER,
    creativity_rank INTEGER,
    creativity_rank_type INTEGER,
    threat_rank INTEGER,
    threat_rank_type INTEGER,
    ict_index_rank INTEGER,
    ict_index_rank_type INTEGER,
    corners_and_indirect_freekicks_order INTEGER,
    corners_and_indirect_freekicks_text TEXT,
    direct_freekicks_order INTEGER,
    direct_freekicks_text TEXT,
    penalties_order INTEGER,
    penalties_text TEXT,
    expected_goals_per_90 REAL,
    saves_per_90 REAL,
    expected_assists_per_90 REAL,
    expected_goal_involvements_per_90 REAL,
    expected_goals_conceded_per_90 REAL,
    goals_conceded_per_90 REAL,
    now_cost_rank INTEGER,
    now_cost_rank_type INTEGER,
    form_rank INTEGER,
    form_rank_type INTEGER,
    points_per_game_rank INTEGER,
    points_per_game_rank_type INTEGER,
    selected_rank INTEGER,
    selected_rank_type INTEGER,
    starts_per_90 REAL,
    clean_sheets_per_90 REAL,
    defensive_contribution_per_90 REAL
);